export const FETCHING_LIST_CONTACT = 'FETCHING_LIST_CONTACT';
export const FETCHING_LIST_CONTACT_SUCCESS = 'FETCHING_LIST_CONTACT_SUCCESS';
export const FETCHING_LIST_CONTACT_ERROR = 'FETCHING_LIST_CONTACT_ERROR';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'; 
export const REMOVE_TO_FAVORITES = 'REMOVE_TO_FAVORITES';
export const LOADING_ADD_TO_FAVORITE = 'LOADING_ADD_TO_FAVORITE'; 
export const FAVORITE_ERROR = 'FAVORITE_ERROR'; 

export const FETCHING_DETAIL_CONTACT = 'FETCHING_DETAIL_CONTACT';
export const FETCHING_DETAIL_CONTACT_SUCCESS = 'FETCHING_DETAIL_CONTACT_SUCCESS';
export const FETCHING_DETAIL_CONTACT_ERROR = 'FETCHING_DETAIL_CONTACT_ERROR';


