export const FETCHING_LIST_CONTACT = 'FETCHING_LIST_CONTACT';
export const FETCHING_LIST_CONTACT_SUCCESS = 'FETCHING_LIST_CONTACT_SUCCESS';
export const FETCHING_LIST_CONTACT_ERROR = 'FETCHING_LIST_CONTACT_ERROR';

